In [ ]:
import pandas as pd


class Icd9Encoder(BaseEstimator, TransformerMixin):

    def __init__(self, comorbidity_df=None):
        self.comorbidity_df = comorbidity_df  # safe, sklearn cloneable

    def fit(self, X, y):
        df = X.copy().reset_index(drop = True)
        y = y.reset_index(drop = True)
        df['target'] = y.values

        com = self.comorbidity_df   # ACCESS HERE SAFELY

        merged = df[['subject_id','hadm_id','target']].merge(
            com, on=['subject_id','hadm_id'], how='left'
        )

        self.icd_mortality_ = merged.groupby('icd9_code')['target'].mean()
        self.global_mean_ = df['target'].mean()
        return self

    def transform(self, X):
        df = X.copy().reset_index(drop = True)
        com = self.comorbidity_df

        merged = df[['subject_id','hadm_id']].merge(
            com, on=['subject_id','hadm_id'], how='left'
        )

        merged['mortality_proxy'] = merged['icd9_code'].map(self.icd_mortality_)
        merged['mortality_proxy'] = merged['mortality_proxy'].fillna(self.global_mean_)

        agg = merged.groupby(['subject_id','hadm_id']).agg(
            max_mortality=('mortality_proxy','max'),
            mean_mortality=('mortality_proxy','mean'),
            count_comorbidities=('icd9_code','count')
        ).reset_index()

        agg = agg.fillna({
            'max_mortality': self.global_mean_,
            'mean_mortality': self.global_mean_,
            'count_comorbidities': 0
        })

        return df.merge(agg, on=['subject_id','hadm_id'], how='left').reset_index(drop = True)

class IndexResetter(BaseEstimator, TransformerMixin):
    def fit(self, X, y=None):
        return self
    def transform(self, X):
        return X.reset_index(drop=True)

In [1]:


test_col = "a"
monkeypatch.setattr(fe, "ICD9_DIAGNOSIS", test_col)

result = change_feature_names(df.copy())

assert result.loc[result['id'] == 1, "a"].iloc[0] == "323", "change_features: patient 1 wrong ICD9"
assert result.loc[result['id'] == 2, "a"].iloc[0] == "409", "change_features: patient 2 wrong ICD9"
assert result.loc[result['id'] == 3, "a"].iloc[0] == "TEE", "change_features: patient 3 wrong ICD9"
assert result.loc[result['id'] == 4, "a"].iloc[0].isna() == True, "change_features: patient 4 wrong ICD9"

IndentationError: unexpected indent (2444280031.py, line 8)

In [10]:
df = pd.DataFrame(
        {
            "FEATURE1": [1,2,3,4,5],
            "FEAT_2": [2,3,4,5,6],
            "ICD_FEATURE": ["44323", "54345", "grgrg", "432dw", None]

        }
    )

In [14]:
df.loc[df['FEATURE1'] == 1, 'ICD_FEATURE']

0    44323
Name: ICD_FEATURE, dtype: object

In [39]:
!source ../.venv/bin/activate

Python(72089) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

In [2]:
import sys
sys.executable

'/Users/gnlm/Desktop/ds_projects/Probability-of-Death-backup/.venv/bin/python'

In [1]:
import pandas as pd
import numpy as np
from probability_of_death.preprocessing.preprocessor import (
    drop_features,
    change_feature_names,
    change_comorbidities_icd9code)
from probability_of_death.feature_engineering.feature_engineering import (
    create_basic_features,
    encoder_demographics,
    encoder_icd9_codes,
    apply_icd9_mapping

)
from probability_of_death.config import DROP_FEATURES, ID_FEATURES, TRAIN_NUMERICAL_FEATURES, TRAIN_CATEGORICAL_FEATURES, TARGET

In [36]:
def random_dates(start, end, n):
    start = pd.to_datetime(start)
    end = pd.to_datetime(end)

    return start + pd.to_timedelta(
        np.random.randint(0, (end - start).days, n), unit="D"
    )


def make_fake_patient_data(n=10):
    base_dates = pd.date_range("2020-01-01", periods=n, freq="D")
    rand_seconds = np.random.randint(0, 24*60*60, size=n)
    admit_times = base_dates + pd.to_timedelta(rand_seconds, unit="s")

    df = pd.DataFrame({
        'DOD': np.arange(n),
        'DISCHTIME': np.arange(n),
        'DEATHTIME': np.arange(n),
        'LOS': np.arange(n),
        "subject_id": np.arange(n),
        "hadm_id": np.arange(100, 100 + n),
        "ADMITTIME": admit_times,
        "RELIGION": ["NONE", "CATHOLIC", None, "JEWISH", "HINDU", "NOT SPECIFIED", "CATHOLIC", None, "UNOBTAINABLE", "HINDU"],
        "MARITAL_STATUS": ["UNKNOWN (DEFAULT)", None, "MARRIED", "DIVORCED", "WIDOWED", "LAF", None, "UNOBTAINABLE", "DIVORCED", "UNKNOWN (DEFAULT)"],
        "ETHNICITY": ["UNABLE TO OBTAIN", "WHITE", None, "BLACK", "HISPANIC", "UNABLE TO OBTAIN", "UNKNOWN/NOT SPECIFIED", None, "UNKNOWN/NOT SPECIFIED", "HISPANIC"],
        "INSURANCE": ["YES", "NO", "YES", "poe", "YES", "NO", "YES", "poe", "YES", "NO"],
        "GENDER": ["Male", None, "Female", "Declined", "None", "Male", None, "Female", None, "Declined)"],
        "ICD9_diagnosis": ["44323", "54345", None, "AB", "004", 2234, "54345", None, 4566, 23],
        "HOSPITAL_EXPIRE_FLAG": [1,0,0,0,1,1,0,0,1,0],
        "icustay_id": np.random.randint(10000,99999,size = n)
        # any required default columns
    })

    return df

def generate_fake_icd_codes(n):
    base_codes = ["44323", "54345", "25000", "41401", "V3000", "AB123"]
    return np.random.choice(base_codes, size=n)

def make_comorbidities_data(n_patients=10, codes_per_patient=3):
    # total rows = n_patients * codes_per_patient
    total = n_patients * codes_per_patient

    subject_ids = np.repeat(np.arange(n_patients), codes_per_patient)
    hadm_ids = np.repeat(np.arange(100, 100 + n_patients), codes_per_patient)

    df = pd.DataFrame({
        "SUBJECT_ID": subject_ids,
        "HADM_ID": hadm_ids,
        "SEQ_NUM": np.tile(np.arange(codes_per_patient), n_patients),
        "ICD9_CODE": generate_fake_icd_codes(total)
    })

    return df

In [43]:
test_df = make_fake_patient_data()
test_df["DOB"] = random_dates("1920-01-01", "2000-12-31", 10)
test_comorbidities_df = make_comorbidities_data()

In [44]:
def preprocess(df, comorbidities_df, icd9_mapping:None):
    df = create_basic_features(df)
    df = encoder_demographics(df)
    df = drop_features(df, DROP_FEATURES)
    df = change_feature_names(df)
    comorbidities_df = change_comorbidities_icd9code(comorbidities_df)
    df,mapping = encoder_icd9_codes(df, comorbidities_df)

    df = df.drop(ID_FEATURES, axis = 1)

    return df, mapping

In [45]:
test_df, test_mapping = preprocess(test_df, test_comorbidities_df, None)

/Users/gnlm/Desktop/ds_projects/Probability-of-Death-backup/src/probability_of_death/feature_engineering/feature_engineering.py:75: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train_df[MAX_MORTALITY] = train_df[MAX_MORTALITY].fillna(0)
/Users/gnlm/Desktop/ds_projects/Probability-of-Death-backup/src/probability_of_death/feature_engineering/feature_engineering.py:76: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train_df[MEAN_MORTALITY] = train_df[MEAN_MORTALITY].fillna(0)
/Users/gnlm/Desktop/ds_projects/Probability-of-Death-backup/src/probability_of_death/feature_engineering/feature_engineering.py:77: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train_df[COUNT_COMORBIDITIES] = train_df[COUNT_COMORBIDITIES].fillna(0)

In [47]:
"HOSPITAL_EXPIRE_FLAG" in test_df.columns

True

In [2]:
train = pd.read_csv("/Users/gnlm/Desktop/ds_projects/Probability-of-Death-backup/data/mimic_train.csv")
train.head()

,HOSPITAL_EXPIRE_FLAG,subject_id,hadm_id,icustay_id,HeartRate_Min,HeartRate_Max,HeartRate_Mean,SysBP_Min,SysBP_Max,SysBP_Mean,...,Diff,ADMISSION_TYPE,INSURANCE,RELIGION,MARITAL_STATUS,ETHNICITY,DIAGNOSIS,ICD9_diagnosis,FIRST_CAREUNIT,LOS
0,0,55440,195768,228357,89.0,145.0,121.043478,74.0,127.0,106.586957,...,-61961.78470,EMERGENCY,Medicare,PROTESTANT QUAKER,SINGLE,WHITE,GASTROINTESTINAL BLEED,5789,MICU,4.5761
1,0,76908,126136,221004,63.0,110.0,79.117647,89.0,121.0,106.733333,...,-43146.18378,EMERGENCY,Private,UNOBTAINABLE,MARRIED,WHITE,ESOPHAGEAL FOOD IMPACTION,53013,MICU,0.7582
2,0,95798,136645,296315,81.0,98.0,91.689655,88.0,138.0,112.785714,...,-42009.96157,EMERGENCY,Medicare,PROTESTANT QUAKER,SEPARATED,BLACK/AFRICAN AMERICAN,UPPER GI BLEED,56983,MICU,3.7626
3,0,40708,102505,245557,76.0,128.0,98.857143,84.0,135.0,106.972973,...,-43585.37922,ELECTIVE,Medicare,NOT SPECIFIED,WIDOWED,WHITE,HIATAL HERNIA/SDA,5533,SICU,3.8734
4,0,28424,127337,225281,NaN,NaN,NaN,NaN,NaN,NaN,...,-50271.76602,EMERGENCY,Medicare,JEWISH,WIDOWED,WHITE,ABDOMINAL PAIN,56211,TSICU,5.8654

In [10]:
0 <= train['HOSPITAL_EXPIRE_FLAG'].all() <=1

np.True_

In [12]:
comor = pd.read_csv('/Users/gnlm/Desktop/ds_projects/Probability-of-Death-backup/data/extra_data/MIMIC_diagnoses.csv')
comor.columns

Index(['SUBJECT_ID', 'HADM_ID', 'SEQ_NUM', 'ICD9_CODE'], dtype='object')

In [38]:
comor

        SUBJECT_ID  HADM_ID  SEQ_NUM ICD9_CODE
0              256   108811      1.0     53240
1              256   108811      2.0     41071
2              256   108811      3.0     53560
3              256   108811      4.0     40390
4              256   108811      5.0      5859
...            ...      ...      ...       ...
651042       65535   178280      5.0      5119
651043       65535   178280      6.0      5990
651044       65535   178280      7.0      0414
651045       65535   178280      8.0     25000
651046       65535   178280      9.0      4019

[651047 rows x 4 columns]

In [45]:
from src.probability_of_death.config import (TRAIN_NUMERICAL_FEATURES,
                                         TRAIN_CATEGORICAL_FEATURES,
                                         DIAGNOSIS,
                                         TARGET,
                                         ICD9_DIAGNOSIS,
                                             ID_FEATURES,
                                             SUBJECT_ID,
                                             HADM_ID,
                                             ICD9_CODE
                                             # C_SUBJECT_ID,
                                             # C_HADM_ID,
                                             # C_SEQ_NUM,
                                             # C_ICD9_CODE
)

C_SUBJECT_ID ='SUBJECT_ID'
C_HADM_ID = 'HADM_ID'
C_SEQ_NUM = 'SEQ_NUM'
C_ICD9_CODE = 'ICD9_CODE'

In [51]:
def make_synthetic_train_data(n = 50, seed = 4201):

    np.random.seed(seed)

    df = pd.DataFrame()

    for feature in TRAIN_NUMERICAL_FEATURES:
        df[feature] = np.random.randn(n)

    for feature in TRAIN_CATEGORICAL_FEATURES:
        df[feature] = np.random.choice(["A", "B", "C", "D", "E"], n)

    for feature in ID_FEATURES:
        df[feature] = np.random.randint(10000, 99999, size = n)

    # df[ICD9_DIAGNOSIS] = np.random.choice(["25000", "4019", "4280", "41401", "2724", "V4581", "51882",
    #                                     "25120", "4019aw", "42820", "41kl401", "272234", "V458ed1", "RE51881"], n)


    df[TARGET] = np.random.choice([0,1], n)
    df[DIAGNOSIS] = np.random.choice(["A123", "B34", "C123", None], n)

    return df

In [39]:
def make_synthetic_comorbidity_data(train_df, rows_per_patient = 3, seed = 4201): # Create id variables that exist in the train data to check merging
    np.random.seed(seed)

    rows = []

    icd9_codes = (
        train_df[ICD9_DIAGNOSIS].dropna().astype(str).unique().tolist()
    )
    noise_codes = ["25000", "4019", "4280", "41401", "2724", "V4581", "51881"]
    all_prefixes = list(set(icd9_codes + noise_codes))
    for _, row in train_df.iterrows():
        subj = row[SUBJECT_ID]
        hadm = row[HADM_ID]

        for seq in range(rows_per_patient):
            prefix = np.random.choice(all_prefixes)
            # icd_full_code = prefix + str(np.random.randint(10, 99))  # add some suffix

            rows.append({
                C_SUBJECT_ID : subj,
                C_HADM_ID : hadm,
                C_SEQ_NUM: seq + 1,
                C_ICD9_CODE: prefix
            })

    return pd.DataFrame(rows)

In [ ]:
C_SUBJECT_ID ='SUBJECT_ID'
C_HADM_ID = 'HADM_ID'
C_SEQ_NUM = 'SEQ_NUM'
C_ICD9_CODE = 'ICD9_CODE'

In [53]:
d = make_synthetic_train_data()
d

,HeartRate_Min,HeartRate_Max,HeartRate_Mean,SysBP_Min,SysBP_Max,SysBP_Mean,DiasBP_Min,DiasBP_Max,DiasBP_Mean,MeanBP_Min,...,count_comorbidities,AGE_AT_ADMIT,ADMISSION_TYPE,FIRST_CAREUNIT,DIAGNOSIS,QUART_DAY,subject_id,hadm_id,icustay_id,HOSPITAL_EXPIRE_FLAG
0,-0.695006,-0.980101,-0.699556,0.720019,-0.341656,-0.252636,-1.855268,0.512276,0.385961,-1.132804,...,-2.666457,1.252293,A,C,B34,D,92773,11699,80960,1
1,-1.791902,-0.592837,0.701794,0.587101,-1.744663,-0.753907,-0.519023,0.124541,-0.844541,-1.512335,...,0.581688,-0.635372,A,C,A123,B,74225,84859,29422,0
2,0.921972,-0.922185,-0.140028,1.150036,-0.174820,0.908685,-0.918200,1.653109,0.203502,0.388524,...,1.006870,1.577429,C,D,A123,A,40176,13468,78436,0
3,-0.483944,2.510178,-0.133058,-1.389249,-0.593578,0.692654,-0.873139,0.368663,2.298194,0.793146,...,0.839672,-0.332280,E,B,None,D,70664,46358,74595,0
4,-0.704517,-0.557355,2.117727,0.504921,-0.207584,0.115288,0.900155,0.505530,0.671575,-0.934065,...,-0.769236,-0.526820,D,B,C123,A,13563,30744,63739,0
5,0.580841,-0.824399,2.489305,0.469803,2.000615,1.053706,-1.195979,0.555427,0.215523,-0.671976,...,-1.255118,0.582932,A,D,C123,C,12864,98081,24761,0
6,0.461438,0.872091,-0.321229,-2.305961,0.121518,0.701814,0.390427,1.103220,-0.402621,-2.145772,...,-2.071655,1.275945,E,E,C123,D,55314,31763,27798,1
7,-0.775023,-0.630804,0.273734,0.306011,1.555520,1.179849,0.497596,0.872957,-1.056240,-0.074955,...,-0.314705,0.254896,E,E,C123,A,18953,86240,43405,0
8,-0.032735,-0.442915,-0.385925,-1.103285,0.179465,0.620307,-1.095026,2.410319,-0.372356,-0.277937,...,-0.854912,1.445790,B,A,B34,E,15187,33371,41796,1
9,-0.091936,-0.058692,2.845677,-0.311536,-0.487323,-0.437876,2.080178,1.795949,0.202492,-0.534802,...,0.340273,0.947724,A,A,None,A,76452,10962,44292,0
10,-1.253252,0.799625,0.307170,-1.034255,0.042069,-1.545563,0.851837,-0.698025,0.334707,0.722464,...,0.291307,-0.562003,A,D,None,A,88250,57648,74508,1
11,-0.966935,-1.120783,-0.449935,-0.463435,1.155637,1.650790,-0.230414,0.290580,0.017948,-0.971112,...,-2.658124,-0.239747,D,B,C123,D,70163,87774,86947,0
12,-0.663709,0.110520,0.858747,0.077085,2.040579,-1.051654,-0.374808,-0.634225,0.914404,0.671317,...,-0.225015,0.790391,D,A,C123,E,60834,43192,65754,0
13,1.367569,1.991353,-0.493618,0.519832,1.550898,0.322107,1.389598,-1.740254,0.525891,-1.294467,...,0.026811,-0.262411,D,B,None,B,93166,54986,44810,1
14,1.133479,-0.701409,1.090425,-0.966970,0.313217,0.897718,-1.278465,-0.557850,-0.546335,1.256210,...,0.862942,-0.914499,D,C,None,C,39963,83173,88434,1
15,-1.578567,-0.386561,-0.417430,1.720195,-0.630933,-0.177712,-0.641380,-0.288271,-1.060672,-0.137995,...,0.046340,1.825237,B,E,A123,A,40674,11118,64275,1
16,0.579401,-0.158854,-0.545193,-0.006871,-0.594646,-1.645430,1.239201,0.644199,0.369900,0.409688,...,-0.924132,0.012622,B,D,A123,B,26157,45229,40008,1
17,0.182333,-0.213566,0.595365,-0.818043,-1.304621,-0.454270,-0.099910,0.616828,1.071596,1.071189,...,1.182713,0.000653,E,B,A123,A,10122,74290,86226,1
18,-0.898500,-1.624139,-0.195554,0.440164,-0.271777,0.240848,0.585108,0.135395,0.145851,2.446170,...,1.110759,0.520199,B,A,None,A,90076,52951,91842,1
19,1.092653,0.550447,0.852310,-1.103293,0.142185,-1.849179,0.680024,-0.116778,0.907334,-1.267100,...,0.100963,-0.549303,C,D,B34,E,43968,51674,88459,0
20,0.268575,-0.001452,-0.676883,0.231985,0.759992,0.376965,-0.263477,-0.124148,-0.294999,0.646460,...,1.331145,-1.087179,B,C,B34,E,76529,52246,93414,0
21,0.200484,-1.280185,-0.947944,1.880719,-0.477526,-0.117058,-0.877499,-0.650293,-0.883137,0.988961,...,-0.719208,1.063687,C,C,None,E,49079,34604,62551,0
22,-0.527830,-0.770751,0.327891,0.361728,-1.040775,0.425494,-0.830840,0.355591,0.478820,0.470561,...,-0.003873,0.711253,C,E,None,C,13964,49406,96025,0
23,-0.326927,0.387466,-0.459416,0.167597,0.324799,0.726604,0.324261,-1.807701,0.778949,0.236797,...,0.642969,0.441561,B,B,C123,E,96271,13204,14306,0
24,-1.646405,-0.650168,-0.346125,1.415994,-0.288421,-1.473195,-2.384412,-0.327200,0.570738,1.032245,...,0.260263,-0.899251,D,D,None,D,13804,20153,80697,1
25,0.693021,-0.823049,0.346012,-0.107269,0.042301,1.034051,0.048248,0.268425,0.161326,-0.950019,...,-0.221735,-1.240444,D,C,C123,A,91849,91357,17739,0
26,-0.629076,-1.116723,0.031450,-0.626046,-1.285978,-1.307615,-0.429891,-0.914050,1.166212,0.859779,...,0.063872,1.615804,E,B,C123,C,58268,88103,73511,0
27,0.193484,-0.985140,-1.891091,-1.285054,-0.488240,-0.015044,-0.290930,1.324370,0.338820,1.450778,...,-0.407519,-0.370764,C,B,C123,E,27525,56710,90291,0
28,-0.876978,-1.111568,0.047064,-2.000071,0.573997,0.173321,0.035214,-0.026417,-0.211295,0.857730,...,2.785093,-0.832655,A,B,A123,C,11909,21523,25243,0
29,-0.750700,0.244056,-0.649699,0.236778,0.351243,0.803741,0.454779,1.763761,1.171695,0.971660,...,-1.162964,-0.336887,A,C,C123,B,70194,13190,30096,1
30,-1.235181,-0.221682,1.030213,0.180022,-0.767695,1.390725,-0.887315,1.289651,0.029124,2.658219,...,1.715872,0.199277,D,C,B34,A,13149,21019,18408,1
31,-1.020509,0.348120,-0.402151,-0.377638,0.051055,0.291041,0.886467,-1.144250,0.572639,-1.596091,...,1.920756,-0.514663,B,A,A123,E,55792,58174,60588,0
32,-0.042215,-1.290347,-1.407730,-0.686995,0.868587,-1.468820,-1.025292,0.239658,-1.095326,0.716010,...,-0.884813,-0.509702,B,E,None,D,36945,60576,72110,1
33,0.760201,-0.147120,-0.853277,1.214430,0.120968,-0.917096,-1.242305,-0.333623,-0.891326,-0.662845,...,-1.747651,-2.053121,B,D,None,B,31174,77588,13569,1
34,0.904572,-0.570072,-0.561932,-2.063194,-0.267321,1.037819,1.479202,-1.247444,0.988878,0.397454,...,-0.296366,0.255223,C,A,A123,A,45212,10421,24670,1
35,-0.234179,-0.595699,0.024175,0.388798,0.848320,1.475387,1.119905,-0.930827,0.514913,-0.185852,...,-0.479633,1.567947,A,E,C123,C,31477,90409,20698,1
36,-2.213318,0.484748,-1.372503,0.385031,1.128356,1.532253,-1.410200,-0.640308,-0.914401,0.963368,...,-0.553871,-0.043644,E,E,C123,D,79951,18292,19946,1
37,0.382066,-1.274366,-0.772997,0.982410,1.345650,-0.091065,-0.505879,2.324198,-0.204352,-0.722660,...,0.974453,-0.154444,B,D,C123,A,65189,78520,74676,0
38,-0.881656,-0.142495,0.589967,-1.138174,0.995310,0.027968,-1.188950,0.016326,-0.566512,1.652935,...,-0.514127,1.011738,A,A,A123,D,58698,13600,94454,1
39,-1.370666,0.223742,0.127404,-0.602756,1.209232,-0.846373,-0.044911,0.854417,0.068532,0.150098,...,0.331164,0.849043,D,D,None,C,36534,33919,21929,1
40,-1.267506,-0.766797,0.918714,0.148108,-0.686630,1.541531,-0.806165,-0.569819,-0.479689,-1.550403,...,-1.410915,0.286203,B,A,C123,A,40190,44084,11787,1
41,0.648591,0.846253,0.422148,2.282868,3.112277,-0.790223,-1.027741,0.792358,-1.551642,0.351057,...,-1.249997,-0.622524,C,A,B34,E,54184,41240,92648,1
42,2.791881,0.042725,-0.923194,0.142109,1.240455,0.094711,0.418268,-0.254155,1.588062,1.563844,...,-1.410783,-0.737814,E,B,A123,B,18646,94212,58912,1
43,0.736205,-0.261450,0.188734,-0.145830,0.654914,0.202971,-0.439448,-2.295173,-1.058739,0.952291,...,-1.115043,-0.964406,B,E,None,E,78217,54781,80073,1
44,0.425084,0.895237,-2.692402,-0.417208,-2.049024,-1.317696,-0.451677,-1.693843,-2.323302,-0.161632,...,1.166045,1.816487,D,E,B34,A,69512,12890,68906,1
45,-1.552588,-1.257907,-2.380691,-0.275118,0.558605,0.404557,1.034655,-0.745635,-1.118703,-0.023040,...,-0.134912,0.113178,D,A,B34,D,38272,74158,57534,1
46,-0.885543,0.951701,1.968227,0.302698,-0.506747,-0.160075,-0.448197,1.000387,-0.755737,2.075271,...,0.614129,-0.167445,D,A,A123,B,69716,17272,39025,1
47,0.287194,-1.283337,0.838051,1.063178,1.129391,1.074079,1.623463,-2.414166,-1.488038,-0.726850,...,-0.289345,-0.134822,C,B,None,C,46929,93247,58446,1
48,-1.772143,0.373924,0.340641,0.693323,-1.096024,-1.204444,-1.607394,-0.212277,0.893360,0.547024,...,0.500591,0.160010,B,B,None,A,77338,91106,89297,0
49,0.706259,-0.911625,-0.250759,0.739008,-0.579522,0.029293,1.010250,1.517590,-0.342794,-0.586150,...,0.477539,-3.016511,D,E,A123,B,64954,80019,60577,1

In [46]:
d2 = make_synthetic_comorbidity_data(d1)

In [47]:
d2

     SUBJECT_ID  HADM_ID  SEQ_NUM ICD9_CODE
0         92773    11699        1   V458ed1
1         92773    11699        2     41401
2         92773    11699        3   RE51881
3         74225    84859        1      4280
4         74225    84859        2     25000
..          ...      ...      ...       ...
145       77338    91106        2   V458ed1
146       77338    91106        3   RE51881
147       64954    80019        1      4280
148       64954    80019        2   RE51881
149       64954    80019        3      2724

[150 rows x 4 columns]

In [ ]:

# def train_model():
#     ########################
#     ### 1. PREPROCESSING ###
#     ########################
#
#     # Load in train data
#     df = pd.read_csv(RAW_DATA_PATH)
#     print("✅ TRAINING DATA LOADED")
#
#     # Create basic features
#     df = create_basic_features(df)
#     print("✅ AGE AND QUARTER-OF-DAY CREATED")
#
#     # Create demographic feature
#     df = encoder_demographics(df)
#     print("✅ DEMOGRAPHIC FEATURES CENSORED AND INTERIM DROPPED")
#
#     #  Drop unused features
#     df = drop_features(df, DROP_FEATURES)
#     print("✅ UNUSED FEATURES DROPPED")
#
#     # Change ICD column names (extract first three chars)
#     df = change_feature_names(df)
#     print("✅ ICD9 CODES SHORTENED - TRAIN")
#
#     # Change ICD9 features (extract first three chars) from comorbidities
#     comorbidities = pd.read_csv(COMORBIDITY_DATA_PATH)
#     comorbidities = change_comorbidities_icd9code(comorbidities)
#     print("✅ ICD9 CODES SHORTENED - COMORBIDITIES")
#
#     # Create target encoding
#     # Encode ICD9 codes
#     df, mapping = encoder_icd9_codes(df, comorbidities)
#
#     print("✅ ICD9 CODE ENCODED")
#
#     # Drop ID features
#     df = df.drop(ID_FEATURES, axis = 1)
#     print("✅ ID FEATURES DROPPED")
#
#     X = df[TRAIN_NUMERICAL_FEATURES + TRAIN_CATEGORICAL_FEATURES]
#     y = df[TARGET]
#
#     ########################
#     ### 2. TRANSFORMERS ###
#     ########################
#     # Encode feature "DIAGNOSOS"
#     diagnosis_encoder = TargetEncoder(
#         cols=['DIAGNOSIS'],
#         smoothing=0.25,  # reduces overfitting
#         handle_missing='value',
#         handle_unknown='value'
#     )
#
#     numeric_transformer = Pipeline(
#         steps=[("imputer", SimpleImputer(strategy="mean")),
#                ("scaler", StandardScaler())])
#
#     categorical_transformer = Pipeline(
#         steps=[("imputer", SimpleImputer(strategy="most_frequent")),
#                ("ohe", OneHotEncoder(handle_unknown='ignore', sparse_output=False))])
#
#     # COMBINE PREPROCESSORS
#     preprocessor = ColumnTransformer(transformers=[
#         ("num", numeric_transformer, TRAIN_NUMERICAL_FEATURES),
#         ("cat", categorical_transformer, TRAIN_CATEGORICAL_FEATURES)],
#         remainder='drop')
#
#     model = xgb.XGBClassifier(**XGB_PARAMS)
#
#     model_pipeline = Pipeline(steps=[
#         ("diagnosis_target_encoder", diagnosis_encoder),
#         ('preprocessor', preprocessor),
#         ('classifier', model)])
#     print("✅ PIPELINE CREATED")
#
#
#     ########################
#     ### 3. TRAIN MODEL ###
#     ########################
#     model_pipeline.fit(X, y)
#     print("✅ MODEL TRAINED")
#
#     # Check model error
#     y_hat_in = model_pipeline.predict(X)
#     print("✅ MODEL RUNS")
#     print(f'1. Model Accuracy:{accuracy_score(y, y_hat_in)} \n2. Model Recall:{recall_score(y, y_hat_in)} \n3. Model Precision: {precision_score(y, y_hat_in)}')
#
#     ########################
#     ### 3. SAVE MODEL ###
#     ########################
#     print("✅ SAVING MODEL")
#     model_path = f"{MODEL_OUTPUT_PATH}/model_{MODEL_VERSION}.pkl"
#     mapping_path = f"{MODEL_OUTPUT_PATH}/icd_mapping_{MODEL_VERSION}.pkl"
#     preprocessor_path = f"{MODEL_OUTPUT_PATH}/preprocessor_{MODEL_VERSION}.pkl"
#
#     joblib.dump(model_pipeline, model_path)
#     joblib.dump(mapping, mapping_path)
#     joblib.dump(preprocessor, preprocessor_path)
#     print("✅ SAVED MODEL")
#
#     return model_pipeline
#

In [ ]:



# def train_model_from_df(df, comorbidities):
#
#     ########################
#     ### 1. PREPROCESSING ####
#     ########################
#
#     # Create basic features
#     df = create_basic_features(df)
#     print("✅ AGE AND QUARTER-OF-DAY CREATED")
#
#     # Create demographic feature
#     df = encoder_demographics(df)
#     print("✅ DEMOGRAPHIC FEATURES CENSORED AND INTERIM DROPPED")
#
#     # Drop unused features
#     df = drop_features(df, DROP_FEATURES)
#     print("✅ UNUSED FEATURES DROPPED")
#
#     # Change ICD column names (extract first three chars)
#     df = change_feature_names(df)
#     print("✅ ICD9 CODES SHORTENED - TRAIN")
#
#     # Shorten comorbid ICD codes
#     comorbidities = change_comorbidities_icd9code(comorbidities)
#     print("✅ ICD9 CODES SHORTENED - COMORBIDITIES")
#
#     # Encode ICD9 comorbidities data
#     df, mapping = encoder_icd9_codes(df, comorbidities)
#     print("✅ ICD9 CODE ENCODED")
#
#     # Drop ID features
#     df = df.drop(ID_FEATURES, axis=1)
#     print("✅ ID FEATURES DROPPED")
#
#     # TRAINING INPUTS
#     X = df[TRAIN_NUMERICAL_FEATURES + TRAIN_CATEGORICAL_FEATURES]
#     y = df[TARGET]
#
#     ########################
#     ### 2. TRANSFORMERS ####
#     ########################
#     diagnosis_encoder = TargetEncoder(
#         cols=['DIAGNOSIS'],
#         smoothing=0.25,
#         handle_missing='value',
#         handle_unknown='value'
#     )
#
#     numeric_transformer = Pipeline([
#         ("imputer", SimpleImputer(strategy="mean")),
#         ("scaler", StandardScaler())
#     ])
#
#     categorical_transformer = Pipeline([
#         ("imputer", SimpleImputer(strategy="most_frequent")),
#         ("ohe", OneHotEncoder(handle_unknown='ignore', sparse_output=False))
#     ])
#
#     preprocessor = ColumnTransformer(
#         transformers=[
#             ("num", numeric_transformer, TRAIN_NUMERICAL_FEATURES),
#             ("cat", categorical_transformer, TRAIN_CATEGORICAL_FEATURES)
#         ],
#         remainder='drop'
#     )
#
#     model = xgb.XGBClassifier(**XGB_PARAMS)
#
#     model_pipeline = Pipeline([
#         ("diagnosis_target_encoder", diagnosis_encoder),
#         ("preprocessor", preprocessor),
#         ("classifier", model)
#     ])
#     print("✅ PIPELINE CREATED")
#
#     ########################
#     ### 3. TRAIN MODEL ###
#     ########################
#     model_pipeline.fit(X, y)
#     print("✅ MODEL TRAINED")
#
#     # Check model error
#     y_hat_in = model_pipeline.predict(X)
#     print("✅ MODEL RUNS")
#     print(
#         f'1. Model Accuracy:{accuracy_score(y, y_hat_in)} \n'
#         f'2. Model Recall:{recall_score(y, y_hat_in)} \n'
#         f'3. Model Precision: {precision_score(y, y_hat_in)}'
#     )
#
#     return model_pipeline, mapping, preprocessor
#
# def train_model():
#     ########################
#     ### 1. PREPROCESSING ###
#     ########################
#
#     df = pd.read_csv(RAW_DATA_PATH)
#     comorbidities = pd.read_csv(COMORBIDITY_DATA_PATH)
#     print("✅ TRAINING DATA LOADED (FROM CSV)")
#
#     model_pipeline, mapping, preprocessor = train_model_from_df(df, comorbidities)
#
#     ########################
#     ### 2. SAVE MODEL ######
#     ########################
#     print("✅ SAVING MODEL")
#     model_path = f"{MODEL_OUTPUT_PATH}/model_{MODEL_VERSION}.pkl"
#     mapping_path = f"{MODEL_OUTPUT_PATH}/icd_mapping_{MODEL_VERSION}.pkl"
#     preprocessor_path = f"{MODEL_OUTPUT_PATH}/preprocessor_{MODEL_VERSION}.pkl"
#
#     joblib.dump(model_pipeline, model_path)
#     joblib.dump(mapping, mapping_path)
#     joblib.dump(preprocessor, preprocessor_path)
#
#     print("✅ SAVED MODEL")
#

In [ ]:
def test_preprocess():
    df = make_fake_patient_data()
    df["DOB"] = random_dates("1920-01-01", "2000-12-31", 10)
    comorbidities_df = make_comorbidities_data()

    df = create_basic_features(df)
    df = encoder_demographics(df)
    df = drop_features(df, DROP_FEATURES)
    df = change_feature_names(df)
    comorbidities_df = change_comorbidities_icd9code(comorbidities_df)
    df,mapping = encoder_icd9_codes(df, comorbidities_df)

    df = df.drop(ID_FEATURES, axis = 1)

    # Assertions
    # New features created - inlcudes mortality features (enocder_demographics)
    for feature in ENGINEERED_MORTALITY_PROXIES + ENGINEERED_NUMERICAL_FEATURES + ENGINEERED_CATEGORICAL_FEATURES:
        assert feature in df.columns, f"feature {feature} present in dataframe"

    # Features dropped
    for feature in DROP_FEATURES:
        assert feature not in df.columns, f"Column {feature} was not dropped"
    # Age
    assert pd.api.types.is_numeric_dtype(df[ENG_AGE])
    assert df[ENG_AGE].between(0, 90).all()
    # Quarter-of-day
    assert df[ENG_QUART_DAY].dtype.name == "category"

    # Demographic missing
    assert set(df[ENG_DEMOGRAPHIC].unique()).issubset({0, 1})

    # Mortality proxies:
    for col in ENGINEERED_MORTALITY_PROXIES:
        assert pd.api.types.is_numeric_dtype(df[col])
    assert df[MAX_MORTALITY].between(0, 1).all()
    assert df[MEAN_MORTALITY].between(0, 1).all()
    assert df[COUNT_COMORBIDITIES].min() >= 0
    assert pd.api.types.is_integer_dtype(df[COUNT_COMORBIDITIES])

In [ ]:
def test_model_saving(trained_model_and_mapping):
    model_path, mapping_path, _ = trained_model_and_mapping

    assert model_path.exists(), "Model doesn't not exist"
    assert mapping_path.exists(), "Mapping doesn't exist"

    loaded_model = joblib.load(model_path)
    loaded_mapping = joblib.load(mapping_path)

    assert hasattr(loaded_model, "predict"), "Model cannot predict"
    assert isinstance(loaded_mapping, pd.DataFrame), "Mapping is not a dataframe"

def test_model_predict(trained_model_and_mapping):
    model_path, _, df_processed = trained_model_and_mapping

    loaded_model = joblib.load(model_path)
    X = df_processed[TRAIN_NUMERICAL_FEATURES + TRAIN_CATEGORICAL_FEATURES]

    prediction = loaded_model.predict(X)
    prediction_proba = loaded_model.predict_proba(X)[:,1]

    assert len(prediction) == len(X), "Prediction length doesn't match"
    assert set(prediction).issubset({0,1}), "Prediction values are outside valide ranges"
    assert pd.Series(prediction_proba).between(0,1).all(), "Prediction probability values are outside valide ranges"